# Generated by Django 5.2.1 on 2025-06-01 16:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News_post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название новости')),
                ('short_description', models.CharField(max_length=200, verbose_name='Краткое описание новости')),
                ('content', models.TextField(verbose_name='Новость')),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Даа публикации')),
            ],
        ),
    ]
